// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAti41rJyJvr5PpMDU9y82p-rdf_bEUSx4',
    appId: '1:572296699419:web:57781f1c34e851f599a2be',
    messagingSenderId: '572296699419',
    projectId: 'notes-c16c6',
    authDomain: 'notes-c16c6.firebaseapp.com',
    storageBucket: 'notes-c16c6.appspot.com',
    measurementId: 'G-KSQ50X43NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv2KN4NQlygWMnAvBg2xwwQd74Dm6mGxY',
    appId: '1:572296699419:android:341c8119576a38cb99a2be',
    messagingSenderId: '572296699419',
    projectId: 'notes-c16c6',
    storageBucket: 'notes-c16c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5kWMMBawLmtxvn2S0R_drruYTr4uOpcM',
    appId: '1:572296699419:ios:73e8e965341325bb99a2be',
    messagingSenderId: '572296699419',
    projectId: 'notes-c16c6',
    storageBucket: 'notes-c16c6.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5kWMMBawLmtxvn2S0R_drruYTr4uOpcM',
    appId: '1:572296699419:ios:82af5762cfb0ec8b99a2be',
    messagingSenderId: '572296699419',
    projectId: 'notes-c16c6',
    storageBucket: 'notes-c16c6.appspot.com',
    iosBundleId: 'com.example.note.RunnerTests',
  );
}
